=== RamsaiKoushik/Data-Masking-Tool/datamasking/DataMaskingTool/src/main/java/datamaskingtool/config/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="db_name" type="xs:string" />
                <xs:element name="username" type="xs:string" />
                <xs:element name="password" type="xs:string" />
                <xs:element name="tables">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="table" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="table_name" type="xs:string" />
                                        <xs:element name="primary_keys">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="primary_key"
                                                        maxOccurs="unbounded" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="unique_columns">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="unique_column"
                                                        maxOccurs="unbounded" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="columns">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="column" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="column_name"
                                                                    type="xs:string" />
                                                                <xs:element name="data_type"
                                                                    type="xs:string" />
                                                                <xs:element name="nullable"
                                                                    type="xs:string" />
                                                                <xs:element name="auto_increment"
                                                                    type="xs:string" />
                                                                <xs:element name="default_value" />
                                                                <xs:element name="masking_strategy"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="foreign_keys">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0">
                                                    <xs:element name="foreign_key" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="foreign_table"
                                                                    type="xs:string" />
                                                                <xs:element name="column_name"
                                                                    type="xs:string" />
                                                                <xs:element name="foreign_column"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RamsaiKoushik/Data-Masking-Tool/datamasking/DataMaskingTool/src/main/java/datamaskingtool/config/config.xml
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="config.xsd">
    <db_name>companydb</db_name>
    <username>root</username>
    <password>Siddhu*kothari04</password>
    <tables>
        <table>
            <table_name>department</table_name>
            <to_mask>Yes</to_mask>
            <primary_keys>
                <primary_key>dnumber</primary_key>
            </primary_keys>
            <unique_columns>
                <unique_column>dnumber</unique_column>
            </unique_columns>
            <columns>
                <column>
                    <column_name>dname</column_name>
                    <data_type>VARCHAR</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>30</column_size>
                    <default_value />
                    <masking_strategy>Shuffle</masking_strategy>
                </column>
                <column>
                    <column_name>dnumber</column_name>
                    <data_type>SMALLINT</data_type>
                    <nullable>NO</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>5</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
                <column>
                    <column_name>mgr_ssn</column_name>
                    <data_type>CHAR</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>9</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
                <column>
                    <column_name>mgr_start_date</column_name>
                    <data_type>DATE</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>10</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
            </columns>
            <foreign_keys />
        </table>
        <table>
            <table_name>dependent</table_name>
            <to_mask>Yes</to_mask>
            <primary_keys>
                <primary_key>dependent_name</primary_key>
                <primary_key>essn</primary_key>
            </primary_keys>
            <unique_columns>
                <unique_column>essn</unique_column>
                <unique_column>dependent_name</unique_column>
            </unique_columns>
            <columns>
                <column>
                    <column_name>essn</column_name>
                    <data_type>CHAR</data_type>
                    <nullable>NO</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>9</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
                <column>
                    <column_name>dependent_name</column_name>
                    <data_type>VARCHAR</data_type>
                    <nullable>NO</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>30</column_size>
                    <default_value />
                    <masking_strategy>PartialRedaction</masking_strategy>
                </column>
                <column>
                    <column_name>sex</column_name>
                    <data_type>CHAR</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>1</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
                <column>
                    <column_name>bdate</column_name>
                    <data_type>DATE</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>10</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
                <column>
                    <column_name>relationship</column_name>
                    <data_type>VARCHAR</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>20</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
            </columns>
            <foreign_keys>
                <foreign_key>
                    <foreign_table>employee</foreign_table>
                    <column_name>essn</column_name>
                    <foreign_column>ssn</foreign_column>
                </foreign_key>
            </foreign_keys>
        </table>
        <table>
            <table_name>dept_locations</table_name>
            <to_mask>Yes</to_mask>
            <primary_keys>
                <primary_key>dlocation</primary_key>
                <primary_key>dnumber</primary_key>
            </primary_keys>
            <unique_columns>
                <unique_column>dlocation</unique_column>
                <unique_column>dnumber</unique_column>
            </unique_columns>
            <columns>
                <column>
                    <column_name>dnumber</column_name>
                    <data_type>SMALLINT</data_type>
                    <nullable>NO</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>5</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
                <column>
                    <column_name>dlocation</column_name>
                    <data_type>VARCHAR</data_type>
                    <nullable>NO</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>20</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
            </columns>
            <foreign_keys>
                <foreign_key>
                    <foreign_table>department</foreign_table>
                    <column_name>dnumber</column_name>
                    <foreign_column>dnumber</foreign_column>
                </foreign_key>
            </foreign_keys>
        </table>
        <table>
            <table_name>employee</table_name>
            <to_mask>Yes</to_mask>
            <primary_keys>
                <primary_key>ssn</primary_key>
            </primary_keys>
            <unique_columns>
                <unique_column>ssn</unique_column>
            </unique_columns>
            <columns>
                <column>
                    <column_name>fname</column_name>
                    <data_type>VARCHAR</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>30</column_size>
                    <default_value />
                    <masking_strategy>Shuffle</masking_strategy>
                </column>
                <column>
                    <column_name>minit</column_name>
                    <data_type>CHAR</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>1</column_size>
                    <default_value />
                    <masking_strategy>Shuffle</masking_strategy>
                </column>
                <column>
                    <column_name>lname</column_name>
                    <data_type>VARCHAR</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>30</column_size>
                    <default_value />
                    <masking_strategy>Shuffle</masking_strategy>
                </column>
                <column>
                    <column_name>ssn</column_name>
                    <data_type>CHAR</data_type>
                    <nullable>NO</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>9</column_size>
                    <default_value />
                    <masking_strategy>Encryption</masking_strategy>
                </column>
                <column>
                    <column_name>bdate</column_name>
                    <data_type>DATE</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>10</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
                <column>
                    <column_name>address</column_name>
                    <data_type>VARCHAR</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>30</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
                <column>
                    <column_name>sex</column_name>
                    <data_type>CHAR</data_type>
                    <nullable>YES</nullable>
                    <auto_increment>NO</auto_increment>
                    <column_size>1</column_size>
                    <default_value />
                    <masking_strategy>no_masking</masking_strategy>
                </column>
                <column>
